linux-nextv: Remove PKG:{PN} which rename to existing package
ERROR: linux-nextv-4.1.37-r0.1 do_package: package "kernel-base" is renamed to "kernel-base" using PKG:kernel-base, but package name already exists